### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by cptolemy** [rjmchi/astrology#1]
Good evening,

Great library, if I may say so :)

Can you just please tell me on which astro formulas did you based the planets position calculation? I see you used the orbital elements, but I don't know from where (Meeus, JPL or maybe other?). And I assume you made no corrections for time light travel, nutation or precession.

Still a good job. I'll wait for your reply if possible.

Kind regards

Ptolemy

**Comment by rjmchi** [comment]
Thanks.  I converted the source code from basic from a book called manual of computer programming for astrologers by michael erlewine.  I can't say I understand any of  it, so I can't say what the calculations are based on.
